"""Registry of parametric part templates.

Every template maps a bounded, known part shape (box, bracket, comb, ...) to one
or more backend-specific generators that render valid parametric source from a
params dict. This is the shared vocabulary both NLU engines (template_matcher
and llm_backend) fill in: neither engine invents geometry outside this
registry, and neither cares which CAD backend eventually consumes the match.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Optional


@dataclass(frozen=True)
class Param:
    name: str
    default: float
    unit: str = "mm"
    description: str = ""
    aliases: tuple[str, ...] = ()


@dataclass(frozen=True)
class Template:
    key: str
    title: str
    keywords: tuple[str, ...]
    params: list[Param]
    generate: Callable[[dict], str]
    generate_freecad: Optional[Callable[[dict], str]] = None
    description: str = ""

    def defaults(self) -> dict:
        return {p.name: p.default for p in self.params}

    def backends(self) -> tuple[str, ...]:
        backends = ["openscad"]
        if self.generate_freecad is not None:
            backends.append("freecad")
        return tuple(backends)


def freecad_macro(template_key: str, param_lines: str, body: str) -> str:
    """Wrap template-specific FreeCAD Part-API code in the doc/export boilerplate
    shared by every template's FreeCAD generator. `body` must assign a Part shape
    to a local variable named `shape`."""
    return f'''# PolyForge FreeCAD macro: {template_key}
# Generated by `polyforge design --backend freecad`. Editable source, like the
# .scad equivalent: re-run design with different params to regenerate rather
# than hand-editing the geometry calls below, unless you're adding a feature
# this template doesn't have.
import os

import FreeCAD
import Part

eps = 0.01

{param_lines}

{body}

# Output is named after this macro's own filename (not the "{template_key}"
# template key) so it matches whatever name `polyforge design --out ...` gave
# it: geometry.freecad_export looks for <macro-stem>.stl/.step.
SCRIPT_PATH = os.path.abspath(__file__)
SCRIPT_DIR = os.path.dirname(SCRIPT_PATH)
STEM = os.path.splitext(os.path.basename(SCRIPT_PATH))[0]

doc = FreeCAD.newDocument(STEM)
obj = doc.addObject("Part::Feature", STEM)
obj.Shape = shape
doc.recompute()

OUTPUT_DIR = os.path.join(SCRIPT_DIR, "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)
shape.exportStl(os.path.join(OUTPUT_DIR, STEM + ".stl"))
Part.export([obj], os.path.join(OUTPUT_DIR, STEM + ".step"))
print("PolyForge: wrote", OUTPUT_DIR)
'''


_REGISTRY: dict[str, Template] = {}


def register(template: Template) -> Template:
    if template.key in _REGISTRY:
        raise ValueError(f"template key already registered: {template.key}")
    _REGISTRY[template.key] = template
    return template


def get(key: str) -> Template:
    try:
        return _REGISTRY[key]
    except KeyError as exc:
        raise KeyError(f"unknown template: {key!r}. Known: {sorted(_REGISTRY)}") from exc


def all_templates() -> list[Template]:
    return list(_REGISTRY.values())
