"""Registry of parametric part templates.

Every template maps a bounded, known part shape (box, bracket, comb, ...) to one
or more backend-specific generators that render valid parametric source from a
params dict. This is the shared vocabulary both NLU engines (template_matcher
and llm_backend) fill in: neither engine invents geometry outside this
registry, and neither cares which CAD backend eventually consumes the match.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Optional


@dataclass(frozen=True)
class Param:
    name: str
    default: float
    unit: str = "mm"
    description: str = ""
    aliases: tuple[str, ...] = ()


@dataclass(frozen=True)
class Template:
    key: str
    title: str
    keywords: tuple[str, ...]
    params: list[Param]
    generate: Callable[[dict], str]
    generate_freecad: Optional[Callable[[dict], str]] = None
    generate_blender: Optional[Callable[[dict], str]] = None
    description: str = ""

    def defaults(self) -> dict:
        return {p.name: p.default for p in self.params}

    def backends(self) -> tuple[str, ...]:
        backends = ["openscad"]
        if self.generate_freecad is not None:
            backends.append("freecad")
        if self.generate_blender is not None:
            backends.append("blender")
        return tuple(backends)


def freecad_macro(template_key: str, param_lines: str, body: str) -> str:
    """Wrap template-specific FreeCAD Part-API code in the doc/export boilerplate
    shared by every template's FreeCAD generator. `body` must assign a Part shape
    to a local variable named `shape`."""
    return f'''# PolyForge FreeCAD macro: {template_key}
# Generated by `polyforge design --backend freecad`. Editable source, like the
# .scad equivalent: re-run design with different params to regenerate rather
# than hand-editing the geometry calls below, unless you're adding a feature
# this template doesn't have.
import os

import FreeCAD
import Part

eps = 0.01

{param_lines}

{body}

# Output is named after this macro's own filename (not the "{template_key}"
# template key) so it matches whatever name `polyforge design --out ...` gave
# it: geometry.freecad_export looks for <macro-stem>.stl/.step.
SCRIPT_PATH = os.path.abspath(__file__)
SCRIPT_DIR = os.path.dirname(SCRIPT_PATH)
STEM = os.path.splitext(os.path.basename(SCRIPT_PATH))[0]

doc = FreeCAD.newDocument(STEM)
obj = doc.addObject("Part::Feature", STEM)
obj.Shape = shape
doc.recompute()

OUTPUT_DIR = os.path.join(SCRIPT_DIR, "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)
shape.exportStl(os.path.join(OUTPUT_DIR, STEM + ".stl"))
Part.export([obj], os.path.join(OUTPUT_DIR, STEM + ".step"))
print("PolyForge: wrote", OUTPUT_DIR)
'''


def blender_macro(template_key: str, param_lines: str, body: str) -> str:
    """Wrap template-specific bpy/bmesh code in the scene-setup/export boilerplate
    shared by every template's Blender generator. `body` must build geometry and
    assign the final solid to a local variable named `result_obj` (a bpy Object
    already linked into the scene collection).

    Unlike FreeCAD's Part API, bpy has no B-rep kernel, so this backend is
    mesh-only: STL export, no STEP. Boolean cuts go through the Boolean
    modifier (EXACT solver) rather than a Part.cut() call.
    """
    return f'''# PolyForge Blender macro: {template_key}
# Generated by `polyforge design --backend blender`. Editable source, like the
# .scad equivalent: re-run design with different params to regenerate rather
# than hand-editing the geometry calls below, unless you're adding a feature
# this template doesn't have.
#
# Run headlessly: blender --background --python this_file.py
# Blender exits 0 even when this script raises -- geometry.blender_export.run()
# detects failure by scanning stdout/stderr for a traceback strictly BETWEEN
# the POLYFORGE_SCRIPT_START/POLYFORGE_SCRIPT_END markers below, not by exit
# code. Blender's own startup/shutdown addon noise (an unrelated bl_pkg import
# failure) prints tracebacks outside that window and must not count.
import os
import math

import bpy
import bmesh

print("POLYFORGE_SCRIPT_START")

eps = 0.01

{param_lines}


def clear_scene():
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete(use_global=False)
    for mesh in list(bpy.data.meshes):
        if mesh.users == 0:
            bpy.data.meshes.remove(mesh)


clear_scene()

{body}

bpy.ops.object.select_all(action='DESELECT')
result_obj.select_set(True)
bpy.context.view_layer.objects.active = result_obj

# Output is named after this macro's own filename (not the "{template_key}"
# template key) so it matches whatever name `polyforge design --out ...` gave
# it: geometry.blender_export looks for <macro-stem>.stl.
SCRIPT_PATH = os.path.abspath(__file__)
SCRIPT_DIR = os.path.dirname(SCRIPT_PATH)
STEM = os.path.splitext(os.path.basename(SCRIPT_PATH))[0]
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)
bpy.ops.wm.stl_export(filepath=os.path.join(OUTPUT_DIR, STEM + ".stl"), export_selected_objects=True)
print("PolyForge: wrote", OUTPUT_DIR)
print("POLYFORGE_SCRIPT_END")
'''


# Shared bmesh box/cylinder/boolean builders, pasted verbatim into every
# generated Blender macro's body (see blender_macro() above) so each .blender.py
# file stays self-contained and independently editable, mirroring how each
# .FCMacro embeds its own small Part-API helpers rather than importing a
# private polyforge module. Cylinder axis convention matches Part.makeCylinder's
# direction vectors already used by the FreeCAD backend: 'Z' == (0, 0, 1),
# 'Y' == (0, 1, 0), 'X' == (1, 0, 0).
BMESH_PRIMITIVES = """def make_box(w, d, h, origin, name):
    bm = bmesh.new()
    v = [
        bm.verts.new((0, 0, 0)), bm.verts.new((w, 0, 0)),
        bm.verts.new((w, d, 0)), bm.verts.new((0, d, 0)),
        bm.verts.new((0, 0, h)), bm.verts.new((w, 0, h)),
        bm.verts.new((w, d, h)), bm.verts.new((0, d, h)),
    ]
    bm.verts.ensure_lookup_table()
    faces = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4), (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
    for f in faces:
        bm.faces.new([v[i] for i in f])
    bmesh.ops.recalc_face_normals(bm, faces=list(bm.faces))
    mesh = bpy.data.meshes.new(name + "_mesh")
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    obj.location = origin
    return obj


def make_cylinder(radius, height, base, axis, name, segs=48):
    bm = bmesh.new()
    verts = [bm.verts.new((radius * math.cos(2 * math.pi * i / segs), radius * math.sin(2 * math.pi * i / segs), 0.0)) for i in range(segs)]
    bm.verts.ensure_lookup_table()
    face = bm.faces.new(verts)
    bmesh.ops.recalc_face_normals(bm, faces=[face])
    ret = bmesh.ops.extrude_face_region(bm, geom=[face])
    top_verts = [v for v in ret['geom'] if isinstance(v, bmesh.types.BMVert)]
    bmesh.ops.translate(bm, verts=top_verts, vec=(0, 0, height))
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    mesh = bpy.data.meshes.new(name + "_mesh")
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    if axis == 'Y':
        obj.rotation_euler = (math.radians(-90), 0, 0)
    elif axis == 'X':
        obj.rotation_euler = (0, math.radians(90), 0)
    obj.location = base
    return obj


def boolean(target, tool, op):
    mod = target.modifiers.new(name="op", type='BOOLEAN')
    mod.operation = op
    mod.object = tool
    mod.solver = 'EXACT'
    bpy.context.view_layer.objects.active = target
    bpy.ops.object.modifier_apply(modifier=mod.name)
    bpy.data.objects.remove(tool, do_unlink=True)
    return target"""


_REGISTRY: dict[str, Template] = {}


def register(template: Template) -> Template:
    if template.key in _REGISTRY:
        raise ValueError(f"template key already registered: {template.key}")
    _REGISTRY[template.key] = template
    return template


def get(key: str) -> Template:
    try:
        return _REGISTRY[key]
    except KeyError as exc:
        raise KeyError(f"unknown template: {key!r}. Known: {sorted(_REGISTRY)}") from exc


def all_templates() -> list[Template]:
    return list(_REGISTRY.values())
